const CLOUDINARY_HOST = 'res.cloudinary.com'

function hasDeliveryTransform(url: string): boolean {
  const marker = '/upload/'
  const idx = url.indexOf(marker)
  if (idx === -1) return false
  const segment = url.slice(idx + marker.length).split('/')[0] ?? ''
  if (/^v\d+$/.test(segment)) return false
  return segment.split(',').some((part) => /^[a-z]{1,3}_/.test(part))
}

/** Cloudinary URLs: auto format/quality and width cap for slow connections. */
export function optimizeImageUrl(
  url: string | null | undefined,
  width = 960,
): string | null | undefined {
  if (!url || !url.includes(CLOUDINARY_HOST) || !url.includes('/upload/')) {
    return url
  }
  if (hasDeliveryTransform(url)) return url

  const transform = `f_auto,q_auto:good,w_${width},c_limit`
  return url.replace('/upload/', `/upload/${transform}/`)
}

/** Prefer WebP sibling for local /images/*.png when present (generated by optimize-images script). */
export function preferWebpSrc(src: string): string {
  if (src.startsWith('/images/') && /\.png$/i.test(src)) {
    return src.replace(/\.png$/i, '.webp')
  }
  return src
}

export function resolveImageSrc(src: string, width = 960): string {
  if (src.includes(CLOUDINARY_HOST)) {
    return optimizeImageUrl(src, width) ?? src
  }
  return preferWebpSrc(src)
}
